site_name: PBP Documentation
repo_url: "https://github.com/mbari-org/pbp-doc/"
edit_uri: "main/docs/"
theme:
  name: 'material'
  logo: https://docs.mbari.org/imgs/mbari-logo.png
  palette:
    - scheme: light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - extra/extra.css

plugins:
  - search
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
      execute: False
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(__md_get("__palette").index == 1)) ? 'dark' : 'light'

extra_javascript:
  - extra/refresh_on_toggle_dark_light.js

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: True

nav:
  - Home: index.md
  - JSON generation: pbp-json-gen/index.md
  - Main program: pbp/index.md
  - Plotting: pbp-plot/index.md
  - Cloud: pbp-cloud/index.md
  - Notebooks: notebooks/index.md
